//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.10.03 at 07:38:36 AM UTC 
//


package se.trixon.trv_traffic_information.road.weathermeasurepoint.v2_1;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Aggregated complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Aggregated"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Wind" type="{}WindConditionAggregated" minOccurs="0"/&gt;
 *         &lt;element name="Precipitation" type="{}PrecipitationConditionAggregated" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Aggregated", propOrder = {
    "wind",
    "precipitation"
})
@XmlSeeAlso({
    Aggregated5Minutes.class,
    Aggregated10Minutes.class,
    Aggregated30Minutes.class
})
public class Aggregated {

    @XmlElement(name = "Wind")
    protected WindConditionAggregated wind;
    @XmlElement(name = "Precipitation")
    protected PrecipitationConditionAggregated precipitation;

    /**
     * Gets the value of the wind property.
     * 
     * @return
     *     possible object is
     *     {@link WindConditionAggregated }
     *     
     */
    public WindConditionAggregated getWind() {
        return wind;
    }

    /**
     * Sets the value of the wind property.
     * 
     * @param value
     *     allowed object is
     *     {@link WindConditionAggregated }
     *     
     */
    public void setWind(WindConditionAggregated value) {
        this.wind = value;
    }

    /**
     * Gets the value of the precipitation property.
     * 
     * @return
     *     possible object is
     *     {@link PrecipitationConditionAggregated }
     *     
     */
    public PrecipitationConditionAggregated getPrecipitation() {
        return precipitation;
    }

    /**
     * Sets the value of the precipitation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrecipitationConditionAggregated }
     *     
     */
    public void setPrecipitation(PrecipitationConditionAggregated value) {
        this.precipitation = value;
    }

}
