//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.10.03 at 07:38:36 AM UTC 
//


package se.trixon.trv_traffic_information.road.weathermeasurepoint.v2_1;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 				Conditions at a certain depth in the ground.
 * 			
 * 
 * <p>Java class for GroundCondition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GroundCondition"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Depth" type="{}IntegerCentimetersConfig" minOccurs="0"/&gt;
 *         &lt;element name="Temperature" type="{}CelsiusMeasure" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GroundCondition", propOrder = {
    "depth",
    "temperature"
})
public class GroundCondition {

    @XmlElement(name = "Depth")
    protected IntegerCentimetersConfig depth;
    @XmlElement(name = "Temperature")
    protected CelsiusMeasure temperature;

    /**
     * Gets the value of the depth property.
     * 
     * @return
     *     possible object is
     *     {@link IntegerCentimetersConfig }
     *     
     */
    public IntegerCentimetersConfig getDepth() {
        return depth;
    }

    /**
     * Sets the value of the depth property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntegerCentimetersConfig }
     *     
     */
    public void setDepth(IntegerCentimetersConfig value) {
        this.depth = value;
    }

    /**
     * Gets the value of the temperature property.
     * 
     * @return
     *     possible object is
     *     {@link CelsiusMeasure }
     *     
     */
    public CelsiusMeasure getTemperature() {
        return temperature;
    }

    /**
     * Sets the value of the temperature property.
     * 
     * @param value
     *     allowed object is
     *     {@link CelsiusMeasure }
     *     
     */
    public void setTemperature(CelsiusMeasure value) {
        this.temperature = value;
    }

}
