//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.10.03 at 07:38:36 AM UTC 
//


package se.trixon.trv_traffic_information.road.weathermeasurepoint.v2_1;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 * 				Observation of road weather, weather and road conditions, at a certain measurement point at a certain time.
 * 			
 * 
 * <p>Java class for ObservationBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ObservationBase"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Sample" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="Weather" type="{}Weather" minOccurs="0"/&gt;
 *         &lt;element name="Surface" type="{}SurfaceCondition" minOccurs="0"/&gt;
 *         &lt;element name="Air" type="{}AirCondition" minOccurs="0"/&gt;
 *         &lt;element name="Wind" type="{}WindCondition" maxOccurs="2" minOccurs="0"/&gt;
 *         &lt;element name="DeicingChemical" type="{}DeicingChemical" minOccurs="0"/&gt;
 *         &lt;element name="Subsurface" type="{}SubsurfaceCondition" minOccurs="0"/&gt;
 *         &lt;element name="Aggregated5minutes" type="{}Aggregated5minutes" minOccurs="0"/&gt;
 *         &lt;element name="Aggregated10minutes" type="{}Aggregated10minutes" minOccurs="0"/&gt;
 *         &lt;element name="Aggregated30minutes" type="{}Aggregated30minutes" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObservationBase", propOrder = {
    "sample",
    "weather",
    "surface",
    "air",
    "wind",
    "deicingChemical",
    "subsurface",
    "aggregated5Minutes",
    "aggregated10Minutes",
    "aggregated30Minutes"
})
@XmlSeeAlso({
    Observation.class
})
public class ObservationBase {

    @XmlElement(name = "Sample")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar sample;
    @XmlElement(name = "Weather")
    protected Weather weather;
    @XmlElement(name = "Surface")
    protected SurfaceCondition surface;
    @XmlElement(name = "Air")
    protected AirCondition air;
    @XmlElement(name = "Wind")
    protected List<WindCondition> wind;
    @XmlElement(name = "DeicingChemical")
    protected DeicingChemical deicingChemical;
    @XmlElement(name = "Subsurface")
    protected SubsurfaceCondition subsurface;
    @XmlElement(name = "Aggregated5minutes")
    protected Aggregated5Minutes aggregated5Minutes;
    @XmlElement(name = "Aggregated10minutes")
    protected Aggregated10Minutes aggregated10Minutes;
    @XmlElement(name = "Aggregated30minutes")
    protected Aggregated30Minutes aggregated30Minutes;

    /**
     * Gets the value of the sample property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSample() {
        return sample;
    }

    /**
     * Sets the value of the sample property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSample(XMLGregorianCalendar value) {
        this.sample = value;
    }

    /**
     * Gets the value of the weather property.
     * 
     * @return
     *     possible object is
     *     {@link Weather }
     *     
     */
    public Weather getWeather() {
        return weather;
    }

    /**
     * Sets the value of the weather property.
     * 
     * @param value
     *     allowed object is
     *     {@link Weather }
     *     
     */
    public void setWeather(Weather value) {
        this.weather = value;
    }

    /**
     * Gets the value of the surface property.
     * 
     * @return
     *     possible object is
     *     {@link SurfaceCondition }
     *     
     */
    public SurfaceCondition getSurface() {
        return surface;
    }

    /**
     * Sets the value of the surface property.
     * 
     * @param value
     *     allowed object is
     *     {@link SurfaceCondition }
     *     
     */
    public void setSurface(SurfaceCondition value) {
        this.surface = value;
    }

    /**
     * Gets the value of the air property.
     * 
     * @return
     *     possible object is
     *     {@link AirCondition }
     *     
     */
    public AirCondition getAir() {
        return air;
    }

    /**
     * Sets the value of the air property.
     * 
     * @param value
     *     allowed object is
     *     {@link AirCondition }
     *     
     */
    public void setAir(AirCondition value) {
        this.air = value;
    }

    /**
     * Gets the value of the wind property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the wind property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWind().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WindCondition }
     * 
     * 
     */
    public List<WindCondition> getWind() {
        if (wind == null) {
            wind = new ArrayList<WindCondition>();
        }
        return this.wind;
    }

    /**
     * Gets the value of the deicingChemical property.
     * 
     * @return
     *     possible object is
     *     {@link DeicingChemical }
     *     
     */
    public DeicingChemical getDeicingChemical() {
        return deicingChemical;
    }

    /**
     * Sets the value of the deicingChemical property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeicingChemical }
     *     
     */
    public void setDeicingChemical(DeicingChemical value) {
        this.deicingChemical = value;
    }

    /**
     * Gets the value of the subsurface property.
     * 
     * @return
     *     possible object is
     *     {@link SubsurfaceCondition }
     *     
     */
    public SubsurfaceCondition getSubsurface() {
        return subsurface;
    }

    /**
     * Sets the value of the subsurface property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubsurfaceCondition }
     *     
     */
    public void setSubsurface(SubsurfaceCondition value) {
        this.subsurface = value;
    }

    /**
     * Gets the value of the aggregated5Minutes property.
     * 
     * @return
     *     possible object is
     *     {@link Aggregated5Minutes }
     *     
     */
    public Aggregated5Minutes getAggregated5Minutes() {
        return aggregated5Minutes;
    }

    /**
     * Sets the value of the aggregated5Minutes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Aggregated5Minutes }
     *     
     */
    public void setAggregated5Minutes(Aggregated5Minutes value) {
        this.aggregated5Minutes = value;
    }

    /**
     * Gets the value of the aggregated10Minutes property.
     * 
     * @return
     *     possible object is
     *     {@link Aggregated10Minutes }
     *     
     */
    public Aggregated10Minutes getAggregated10Minutes() {
        return aggregated10Minutes;
    }

    /**
     * Sets the value of the aggregated10Minutes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Aggregated10Minutes }
     *     
     */
    public void setAggregated10Minutes(Aggregated10Minutes value) {
        this.aggregated10Minutes = value;
    }

    /**
     * Gets the value of the aggregated30Minutes property.
     * 
     * @return
     *     possible object is
     *     {@link Aggregated30Minutes }
     *     
     */
    public Aggregated30Minutes getAggregated30Minutes() {
        return aggregated30Minutes;
    }

    /**
     * Sets the value of the aggregated30Minutes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Aggregated30Minutes }
     *     
     */
    public void setAggregated30Minutes(Aggregated30Minutes value) {
        this.aggregated30Minutes = value;
    }

}
