//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.10.03 at 07:38:36 AM UTC 
//


package se.trixon.trv_traffic_information.road.weathermeasurepoint.v2_1;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PrecipTypeMeasure.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PrecipTypeMeasure"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="no"/&gt;
 *     &lt;enumeration value="rain"/&gt;
 *     &lt;enumeration value="freezing_rain"/&gt;
 *     &lt;enumeration value="snow"/&gt;
 *     &lt;enumeration value="sleet"/&gt;
 *     &lt;enumeration value="yes"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "PrecipTypeMeasure")
@XmlEnum
public enum PrecipTypeMeasure {

    @XmlEnumValue("no")
    NO("no"),
    @XmlEnumValue("rain")
    RAIN("rain"),
    @XmlEnumValue("freezing_rain")
    FREEZING_RAIN("freezing_rain"),
    @XmlEnumValue("snow")
    SNOW("snow"),
    @XmlEnumValue("sleet")
    SLEET("sleet"),
    @XmlEnumValue("yes")
    YES("yes");
    private final String value;

    PrecipTypeMeasure(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PrecipTypeMeasure fromValue(String v) {
        for (PrecipTypeMeasure c: PrecipTypeMeasure.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
