//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.10.03 at 07:38:36 AM UTC 
//


package se.trixon.trv_traffic_information.road.weathermeasurepoint.v2_1;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PrecipitationConditionAggregated complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PrecipitationConditionAggregated"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Rain" type="{}BoolMeasure" minOccurs="0"/&gt;
 *         &lt;element name="Snow" type="{}BoolMeasure" minOccurs="0"/&gt;
 *         &lt;element name="RainSum" type="{}MillimetersMeasure" minOccurs="0"/&gt;
 *         &lt;element name="SnowSum" type="{}SnowAmount" minOccurs="0"/&gt;
 *         &lt;element name="TotalWaterEquivalent" type="{}MillimetersMeasure" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PrecipitationConditionAggregated", propOrder = {
    "rain",
    "snow",
    "rainSum",
    "snowSum",
    "totalWaterEquivalent"
})
public class PrecipitationConditionAggregated {

    @XmlElement(name = "Rain")
    protected BoolMeasure rain;
    @XmlElement(name = "Snow")
    protected BoolMeasure snow;
    @XmlElement(name = "RainSum")
    protected MillimetersMeasure rainSum;
    @XmlElement(name = "SnowSum")
    protected SnowAmount snowSum;
    @XmlElement(name = "TotalWaterEquivalent")
    protected MillimetersMeasure totalWaterEquivalent;

    /**
     * Gets the value of the rain property.
     * 
     * @return
     *     possible object is
     *     {@link BoolMeasure }
     *     
     */
    public BoolMeasure getRain() {
        return rain;
    }

    /**
     * Sets the value of the rain property.
     * 
     * @param value
     *     allowed object is
     *     {@link BoolMeasure }
     *     
     */
    public void setRain(BoolMeasure value) {
        this.rain = value;
    }

    /**
     * Gets the value of the snow property.
     * 
     * @return
     *     possible object is
     *     {@link BoolMeasure }
     *     
     */
    public BoolMeasure getSnow() {
        return snow;
    }

    /**
     * Sets the value of the snow property.
     * 
     * @param value
     *     allowed object is
     *     {@link BoolMeasure }
     *     
     */
    public void setSnow(BoolMeasure value) {
        this.snow = value;
    }

    /**
     * Gets the value of the rainSum property.
     * 
     * @return
     *     possible object is
     *     {@link MillimetersMeasure }
     *     
     */
    public MillimetersMeasure getRainSum() {
        return rainSum;
    }

    /**
     * Sets the value of the rainSum property.
     * 
     * @param value
     *     allowed object is
     *     {@link MillimetersMeasure }
     *     
     */
    public void setRainSum(MillimetersMeasure value) {
        this.rainSum = value;
    }

    /**
     * Gets the value of the snowSum property.
     * 
     * @return
     *     possible object is
     *     {@link SnowAmount }
     *     
     */
    public SnowAmount getSnowSum() {
        return snowSum;
    }

    /**
     * Sets the value of the snowSum property.
     * 
     * @param value
     *     allowed object is
     *     {@link SnowAmount }
     *     
     */
    public void setSnowSum(SnowAmount value) {
        this.snowSum = value;
    }

    /**
     * Gets the value of the totalWaterEquivalent property.
     * 
     * @return
     *     possible object is
     *     {@link MillimetersMeasure }
     *     
     */
    public MillimetersMeasure getTotalWaterEquivalent() {
        return totalWaterEquivalent;
    }

    /**
     * Sets the value of the totalWaterEquivalent property.
     * 
     * @param value
     *     allowed object is
     *     {@link MillimetersMeasure }
     *     
     */
    public void setTotalWaterEquivalent(MillimetersMeasure value) {
        this.totalWaterEquivalent = value;
    }

}
