//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.10.03 at 07:38:36 AM UTC 
//


package se.trixon.trv_traffic_information.road.weathermeasurepoint.v2_1;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WindConditionAggregated complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WindConditionAggregated"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Height" type="{}WindSensorHeight" minOccurs="0"/&gt;
 *         &lt;element name="SpeedMax" type="{}MetersPerSecondMeasure" minOccurs="0"/&gt;
 *         &lt;element name="SpeedAverage" type="{}MetersPerSecondMeasure" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WindConditionAggregated", propOrder = {
    "height",
    "speedMax",
    "speedAverage"
})
public class WindConditionAggregated {

    @XmlElement(name = "Height")
    protected Integer height;
    @XmlElement(name = "SpeedMax")
    protected MetersPerSecondMeasure speedMax;
    @XmlElement(name = "SpeedAverage")
    protected MetersPerSecondMeasure speedAverage;

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHeight(Integer value) {
        this.height = value;
    }

    /**
     * Gets the value of the speedMax property.
     * 
     * @return
     *     possible object is
     *     {@link MetersPerSecondMeasure }
     *     
     */
    public MetersPerSecondMeasure getSpeedMax() {
        return speedMax;
    }

    /**
     * Sets the value of the speedMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetersPerSecondMeasure }
     *     
     */
    public void setSpeedMax(MetersPerSecondMeasure value) {
        this.speedMax = value;
    }

    /**
     * Gets the value of the speedAverage property.
     * 
     * @return
     *     possible object is
     *     {@link MetersPerSecondMeasure }
     *     
     */
    public MetersPerSecondMeasure getSpeedAverage() {
        return speedAverage;
    }

    /**
     * Sets the value of the speedAverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetersPerSecondMeasure }
     *     
     */
    public void setSpeedAverage(MetersPerSecondMeasure value) {
        this.speedAverage = value;
    }

}
