//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.10.03 at 07:38:36 AM UTC 
//


package se.trixon.trv_traffic_information.road.weathermeasurepoint.v2_1;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 				Wind conditions close to the ground.
 * 			
 * 
 * <p>Java class for WindCondition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WindCondition"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Height" type="{}WindSensorHeight" minOccurs="0"/&gt;
 *         &lt;element name="Speed" type="{}MetersPerSecondMeasure" minOccurs="0"/&gt;
 *         &lt;element name="Direction" type="{}DegreesMeasure" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WindCondition", propOrder = {
    "height",
    "speed",
    "direction"
})
public class WindCondition {

    @XmlElement(name = "Height")
    protected Integer height;
    @XmlElement(name = "Speed")
    protected MetersPerSecondMeasure speed;
    @XmlElement(name = "Direction")
    protected DegreesMeasure direction;

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHeight(Integer value) {
        this.height = value;
    }

    /**
     * Gets the value of the speed property.
     * 
     * @return
     *     possible object is
     *     {@link MetersPerSecondMeasure }
     *     
     */
    public MetersPerSecondMeasure getSpeed() {
        return speed;
    }

    /**
     * Sets the value of the speed property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetersPerSecondMeasure }
     *     
     */
    public void setSpeed(MetersPerSecondMeasure value) {
        this.speed = value;
    }

    /**
     * Gets the value of the direction property.
     * 
     * @return
     *     possible object is
     *     {@link DegreesMeasure }
     *     
     */
    public DegreesMeasure getDirection() {
        return direction;
    }

    /**
     * Sets the value of the direction property.
     * 
     * @param value
     *     allowed object is
     *     {@link DegreesMeasure }
     *     
     */
    public void setDirection(DegreesMeasure value) {
        this.direction = value;
    }

}
