//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.10.04 at 07:12:40 AM UTC
//
package se.trixon.trv_traffic_information.road.camera.v1_1;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for Camera complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="Camera"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Active" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="CameraGroup" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ContentType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CountyNo" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}Deleted" minOccurs="0"/&gt;
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Direction" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="HasFullSizePhoto" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="HasSketchImage" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="IconId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Location" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PhotoTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="PhotoUrl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PhotoUrlFullsize" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PhotoUrlThumbnail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PhotoUrlSketch" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Geometry" type="{}geometry" minOccurs="0"/&gt;
 *         &lt;element name="ModifiedTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{}QueueAttributes"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Camera", propOrder = {
    "active",
    "cameraGroup",
    "contentType",
    "countyNo",
    "deleted",
    "description",
    "direction",
    "hasFullSizePhoto",
    "hasSketchImage",
    "iconId",
    "id",
    "location",
    "name",
    "type",
    "photoTime",
    "photoUrl",
    "photoUrlFullsize",
    "photoUrlThumbnail",
    "photoUrlSketch",
    "status",
    "geometry",
    "modifiedTime"
})
public class Camera {

    @XmlElement(name = "Active")
    protected Boolean active;
    @XmlElement(name = "CameraGroup")
    protected String cameraGroup;
    @XmlElement(name = "ContentType")
    protected String contentType;
    @XmlElement(name = "CountyNo", type = Integer.class)
    protected List<Integer> countyNo;
    @XmlElement(name = "Deleted", defaultValue = "false")
    protected Boolean deleted;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "Direction")
    protected Integer direction;
    @XmlElement(name = "HasFullSizePhoto")
    protected Boolean hasFullSizePhoto;
    @XmlElement(name = "HasSketchImage")
    protected Boolean hasSketchImage;
    @XmlElement(name = "IconId")
    protected String iconId;
    @XmlElement(name = "Id")
    protected String id;
    @XmlElement(name = "Location")
    protected String location;
    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "Type")
    protected String type;
    @XmlElement(name = "PhotoTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar photoTime;
    @XmlElement(name = "PhotoUrl")
    protected String photoUrl;
    @XmlElement(name = "PhotoUrlFullsize")
    protected String photoUrlFullsize;
    @XmlElement(name = "PhotoUrlThumbnail")
    protected String photoUrlThumbnail;
    @XmlElement(name = "PhotoUrlSketch")
    protected String photoUrlSketch;
    @XmlElement(name = "Status")
    protected String status;
    @XmlElement(name = "Geometry")
    protected Geometry geometry;
    @XmlElement(name = "ModifiedTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar modifiedTime;
    @XmlAttribute(name = "checkoutid")
    protected String checkoutid;
    @XmlAttribute(name = "checkouts")
    protected BigInteger checkouts;
    @XmlAttribute(name = "leaseduntil")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar leaseduntil;
    @XmlAttribute(name = "acknowledged")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar acknowledged;
    @XmlAttribute(name = "statuscode")
    @XmlSchemaType(name = "unsignedByte")
    protected Short statuscode;
    @XmlAttribute(name = "itemsacknowledged")
    protected Long itemsacknowledged;
    @XmlAttribute(name = "itemsleft")
    protected Long itemsleft;

    /**
     * Gets the value of the active property.
     *
     * @return possible object is {@link Boolean }
     *
     */
    public Boolean isActive() {
        return active;
    }

    /**
     * Sets the value of the active property.
     *
     * @param value allowed object is {@link Boolean }
     *
     */
    public void setActive(Boolean value) {
        this.active = value;
    }

    /**
     * Gets the value of the cameraGroup property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getCameraGroup() {
        return cameraGroup;
    }

    /**
     * Sets the value of the cameraGroup property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setCameraGroup(String value) {
        this.cameraGroup = value;
    }

    /**
     * Gets the value of the contentType property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * Sets the value of the contentType property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setContentType(String value) {
        this.contentType = value;
    }

    /**
     * Gets the value of the countyNo property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the countyNo property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCountyNo().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Integer }
     *
     *
     */
    public List<Integer> getCountyNo() {
        if (countyNo == null) {
            countyNo = new ArrayList<Integer>();
        }
        return this.countyNo;
    }

    /**
     * Gets the value of the deleted property.
     *
     * @return possible object is {@link Boolean }
     *
     */
    public Boolean isDeleted() {
        return deleted;
    }

    /**
     * Sets the value of the deleted property.
     *
     * @param value allowed object is {@link Boolean }
     *
     */
    public void setDeleted(Boolean value) {
        this.deleted = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the direction property.
     *
     * @return possible object is {@link Integer }
     *
     */
    public Integer getDirection() {
        return direction;
    }

    /**
     * Sets the value of the direction property.
     *
     * @param value allowed object is {@link Integer }
     *
     */
    public void setDirection(Integer value) {
        this.direction = value;
    }

    /**
     * Gets the value of the hasFullSizePhoto property.
     *
     * @return possible object is {@link Boolean }
     *
     */
    public Boolean isHasFullSizePhoto() {
        return hasFullSizePhoto;
    }

    /**
     * Sets the value of the hasFullSizePhoto property.
     *
     * @param value allowed object is {@link Boolean }
     *
     */
    public void setHasFullSizePhoto(Boolean value) {
        this.hasFullSizePhoto = value;
    }

    /**
     * Gets the value of the hasSketchImage property.
     *
     * @return possible object is {@link Boolean }
     *
     */
    public Boolean isHasSketchImage() {
        return hasSketchImage;
    }

    /**
     * Sets the value of the hasSketchImage property.
     *
     * @param value allowed object is {@link Boolean }
     *
     */
    public void setHasSketchImage(Boolean value) {
        this.hasSketchImage = value;
    }

    /**
     * Gets the value of the iconId property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getIconId() {
        return iconId;
    }

    /**
     * Sets the value of the iconId property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setIconId(String value) {
        this.iconId = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the location property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setLocation(String value) {
        this.location = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the photoTime property.
     *
     * @return possible object is {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getPhotoTime() {
        return photoTime;
    }

    /**
     * Sets the value of the photoTime property.
     *
     * @param value allowed object is {@link XMLGregorianCalendar }
     *
     */
    public void setPhotoTime(XMLGregorianCalendar value) {
        this.photoTime = value;
    }

    /**
     * Gets the value of the photoUrl property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getPhotoUrl() {
        return photoUrl;
    }

    /**
     * Sets the value of the photoUrl property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setPhotoUrl(String value) {
        this.photoUrl = value;
    }

    /**
     * Gets the value of the photoUrlFullsize property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getPhotoUrlFullsize() {
        return photoUrlFullsize;
    }

    /**
     * Sets the value of the photoUrlFullsize property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setPhotoUrlFullsize(String value) {
        this.photoUrlFullsize = value;
    }

    /**
     * Gets the value of the photoUrlThumbnail property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getPhotoUrlThumbnail() {
        return photoUrlThumbnail;
    }

    /**
     * Sets the value of the photoUrlThumbnail property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setPhotoUrlThumbnail(String value) {
        this.photoUrlThumbnail = value;
    }

    /**
     * Gets the value of the photoUrlSketch property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getPhotoUrlSketch() {
        return photoUrlSketch;
    }

    /**
     * Sets the value of the photoUrlSketch property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setPhotoUrlSketch(String value) {
        this.photoUrlSketch = value;
    }

    /**
     * Gets the value of the status property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the geometry property.
     *
     * @return possible object is {@link Geometry }
     *
     */
    public Geometry getGeometry() {
        return geometry;
    }

    /**
     * Sets the value of the geometry property.
     *
     * @param value allowed object is {@link Geometry }
     *
     */
    public void setGeometry(Geometry value) {
        this.geometry = value;
    }

    /**
     * Gets the value of the modifiedTime property.
     *
     * @return possible object is {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getModifiedTime() {
        return modifiedTime;
    }

    /**
     * Sets the value of the modifiedTime property.
     *
     * @param value allowed object is {@link XMLGregorianCalendar }
     *
     */
    public void setModifiedTime(XMLGregorianCalendar value) {
        this.modifiedTime = value;
    }

    /**
     * Gets the value of the checkoutid property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getCheckoutid() {
        return checkoutid;
    }

    /**
     * Sets the value of the checkoutid property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setCheckoutid(String value) {
        this.checkoutid = value;
    }

    /**
     * Gets the value of the checkouts property.
     *
     * @return possible object is {@link BigInteger }
     *
     */
    public BigInteger getCheckouts() {
        return checkouts;
    }

    /**
     * Sets the value of the checkouts property.
     *
     * @param value allowed object is {@link BigInteger }
     *
     */
    public void setCheckouts(BigInteger value) {
        this.checkouts = value;
    }

    /**
     * Gets the value of the leaseduntil property.
     *
     * @return possible object is {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getLeaseduntil() {
        return leaseduntil;
    }

    /**
     * Sets the value of the leaseduntil property.
     *
     * @param value allowed object is {@link XMLGregorianCalendar }
     *
     */
    public void setLeaseduntil(XMLGregorianCalendar value) {
        this.leaseduntil = value;
    }

    /**
     * Gets the value of the acknowledged property.
     *
     * @return possible object is {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getAcknowledged() {
        return acknowledged;
    }

    /**
     * Sets the value of the acknowledged property.
     *
     * @param value allowed object is {@link XMLGregorianCalendar }
     *
     */
    public void setAcknowledged(XMLGregorianCalendar value) {
        this.acknowledged = value;
    }

    /**
     * Gets the value of the statuscode property.
     *
     * @return possible object is {@link Short }
     *
     */
    public Short getStatuscode() {
        return statuscode;
    }

    /**
     * Sets the value of the statuscode property.
     *
     * @param value allowed object is {@link Short }
     *
     */
    public void setStatuscode(Short value) {
        this.statuscode = value;
    }

    /**
     * Gets the value of the itemsacknowledged property.
     *
     * @return possible object is {@link Long }
     *
     */
    public Long getItemsacknowledged() {
        return itemsacknowledged;
    }

    /**
     * Sets the value of the itemsacknowledged property.
     *
     * @param value allowed object is {@link Long }
     *
     */
    public void setItemsacknowledged(Long value) {
        this.itemsacknowledged = value;
    }

    /**
     * Gets the value of the itemsleft property.
     *
     * @return possible object is {@link Long }
     *
     */
    public Long getItemsleft() {
        return itemsleft;
    }

    /**
     * Sets the value of the itemsleft property.
     *
     * @param value allowed object is {@link Long }
     *
     */
    public void setItemsleft(Long value) {
        this.itemsleft = value;
    }

}
