//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.29 at 02:40:55 PM UTC 
//


package se.trixon.trv_trafikinformation.jarnvag.trainannouncement.v1_6;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TrainAnnouncement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrainAnnouncement"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ActivityId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ActivityType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Advertised" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="AdvertisedTimeAtLocation" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="AdvertisedTrainIdent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Booking" type="{}Booking" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Canceled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="Deleted" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="Deviation" type="{}Deviation" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="EstimatedTimeAtLocation" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="EstimatedTimeIsPreliminary" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="FromLocation" type="{}FromLocation" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="InformationOwner" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LocationSignature" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MobileWebLink" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ModifiedTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="NewEquipment" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="Operator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="OtherInformation" type="{}OtherInformation" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="PlannedEstimatedTimeAtLocation" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="PlannedEstimatedTimeAtLocationIsValid" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="ProductInformation" type="{}ProductInformation" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="ScheduledDepartureDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="Service" type="{}Service" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="TechnicalDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="TechnicalTrainIdent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TimeAtLocation" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="TimeAtLocationWithSeconds" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="ToLocation" type="{}ToLocation" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="TrackAtLocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TrainComposition" type="{}TrainComposition" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="TrainOwner" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TypeOfTraffic" type="{}TypeOfTraffic" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="ViaFromLocation" type="{}ViaFromLocation" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="ViaToLocation" type="{}ViaToLocation" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="WebLink" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="WebLinkName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrainAnnouncement", propOrder = {
    "activityId",
    "activityType",
    "advertised",
    "advertisedTimeAtLocation",
    "advertisedTrainIdent",
    "booking",
    "canceled",
    "deleted",
    "deviation",
    "estimatedTimeAtLocation",
    "estimatedTimeIsPreliminary",
    "fromLocation",
    "informationOwner",
    "locationSignature",
    "mobileWebLink",
    "modifiedTime",
    "newEquipment",
    "operator",
    "otherInformation",
    "plannedEstimatedTimeAtLocation",
    "plannedEstimatedTimeAtLocationIsValid",
    "productInformation",
    "scheduledDepartureDateTime",
    "service",
    "technicalDateTime",
    "technicalTrainIdent",
    "timeAtLocation",
    "timeAtLocationWithSeconds",
    "toLocation",
    "trackAtLocation",
    "trainComposition",
    "trainOwner",
    "typeOfTraffic",
    "viaFromLocation",
    "viaToLocation",
    "webLink",
    "webLinkName"
})
public class TrainAnnouncement {

    @XmlElement(name = "ActivityId")
    protected String activityId;
    @XmlElement(name = "ActivityType")
    protected String activityType;
    @XmlElement(name = "Advertised")
    protected Boolean advertised;
    @XmlElement(name = "AdvertisedTimeAtLocation")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar advertisedTimeAtLocation;
    @XmlElement(name = "AdvertisedTrainIdent")
    protected String advertisedTrainIdent;
    @XmlElement(name = "Booking")
    protected List<Booking> booking;
    @XmlElement(name = "Canceled")
    protected Boolean canceled;
    @XmlElement(name = "Deleted")
    protected Boolean deleted;
    @XmlElement(name = "Deviation")
    protected List<Deviation> deviation;
    @XmlElement(name = "EstimatedTimeAtLocation")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar estimatedTimeAtLocation;
    @XmlElement(name = "EstimatedTimeIsPreliminary")
    protected Boolean estimatedTimeIsPreliminary;
    @XmlElement(name = "FromLocation")
    protected List<FromLocation> fromLocation;
    @XmlElement(name = "InformationOwner")
    protected String informationOwner;
    @XmlElement(name = "LocationSignature")
    protected String locationSignature;
    @XmlElement(name = "MobileWebLink")
    protected String mobileWebLink;
    @XmlElement(name = "ModifiedTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar modifiedTime;
    @XmlElement(name = "NewEquipment")
    protected Integer newEquipment;
    @XmlElement(name = "Operator")
    protected String operator;
    @XmlElement(name = "OtherInformation")
    protected List<OtherInformation> otherInformation;
    @XmlElement(name = "PlannedEstimatedTimeAtLocation")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar plannedEstimatedTimeAtLocation;
    @XmlElement(name = "PlannedEstimatedTimeAtLocationIsValid")
    protected Boolean plannedEstimatedTimeAtLocationIsValid;
    @XmlElement(name = "ProductInformation")
    protected List<ProductInformation> productInformation;
    @XmlElement(name = "ScheduledDepartureDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar scheduledDepartureDateTime;
    @XmlElement(name = "Service")
    protected List<Service> service;
    @XmlElement(name = "TechnicalDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar technicalDateTime;
    @XmlElement(name = "TechnicalTrainIdent")
    protected String technicalTrainIdent;
    @XmlElement(name = "TimeAtLocation")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeAtLocation;
    @XmlElement(name = "TimeAtLocationWithSeconds")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeAtLocationWithSeconds;
    @XmlElement(name = "ToLocation")
    protected List<ToLocation> toLocation;
    @XmlElement(name = "TrackAtLocation")
    protected String trackAtLocation;
    @XmlElement(name = "TrainComposition")
    protected List<TrainComposition> trainComposition;
    @XmlElement(name = "TrainOwner")
    protected String trainOwner;
    @XmlElement(name = "TypeOfTraffic")
    protected List<TypeOfTraffic> typeOfTraffic;
    @XmlElement(name = "ViaFromLocation")
    protected List<ViaFromLocation> viaFromLocation;
    @XmlElement(name = "ViaToLocation")
    protected List<ViaToLocation> viaToLocation;
    @XmlElement(name = "WebLink")
    protected String webLink;
    @XmlElement(name = "WebLinkName")
    protected String webLinkName;

    /**
     * Gets the value of the activityId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivityId() {
        return activityId;
    }

    /**
     * Sets the value of the activityId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivityId(String value) {
        this.activityId = value;
    }

    /**
     * Gets the value of the activityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivityType() {
        return activityType;
    }

    /**
     * Sets the value of the activityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivityType(String value) {
        this.activityType = value;
    }

    /**
     * Gets the value of the advertised property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAdvertised() {
        return advertised;
    }

    /**
     * Sets the value of the advertised property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAdvertised(Boolean value) {
        this.advertised = value;
    }

    /**
     * Gets the value of the advertisedTimeAtLocation property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAdvertisedTimeAtLocation() {
        return advertisedTimeAtLocation;
    }

    /**
     * Sets the value of the advertisedTimeAtLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAdvertisedTimeAtLocation(XMLGregorianCalendar value) {
        this.advertisedTimeAtLocation = value;
    }

    /**
     * Gets the value of the advertisedTrainIdent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdvertisedTrainIdent() {
        return advertisedTrainIdent;
    }

    /**
     * Sets the value of the advertisedTrainIdent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdvertisedTrainIdent(String value) {
        this.advertisedTrainIdent = value;
    }

    /**
     * Gets the value of the booking property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the booking property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBooking().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Booking }
     * 
     * 
     */
    public List<Booking> getBooking() {
        if (booking == null) {
            booking = new ArrayList<Booking>();
        }
        return this.booking;
    }

    /**
     * Gets the value of the canceled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCanceled() {
        return canceled;
    }

    /**
     * Sets the value of the canceled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCanceled(Boolean value) {
        this.canceled = value;
    }

    /**
     * Gets the value of the deleted property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDeleted() {
        return deleted;
    }

    /**
     * Sets the value of the deleted property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDeleted(Boolean value) {
        this.deleted = value;
    }

    /**
     * Gets the value of the deviation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deviation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeviation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Deviation }
     * 
     * 
     */
    public List<Deviation> getDeviation() {
        if (deviation == null) {
            deviation = new ArrayList<Deviation>();
        }
        return this.deviation;
    }

    /**
     * Gets the value of the estimatedTimeAtLocation property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEstimatedTimeAtLocation() {
        return estimatedTimeAtLocation;
    }

    /**
     * Sets the value of the estimatedTimeAtLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEstimatedTimeAtLocation(XMLGregorianCalendar value) {
        this.estimatedTimeAtLocation = value;
    }

    /**
     * Gets the value of the estimatedTimeIsPreliminary property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEstimatedTimeIsPreliminary() {
        return estimatedTimeIsPreliminary;
    }

    /**
     * Sets the value of the estimatedTimeIsPreliminary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEstimatedTimeIsPreliminary(Boolean value) {
        this.estimatedTimeIsPreliminary = value;
    }

    /**
     * Gets the value of the fromLocation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fromLocation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFromLocation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FromLocation }
     * 
     * 
     */
    public List<FromLocation> getFromLocation() {
        if (fromLocation == null) {
            fromLocation = new ArrayList<FromLocation>();
        }
        return this.fromLocation;
    }

    /**
     * Gets the value of the informationOwner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInformationOwner() {
        return informationOwner;
    }

    /**
     * Sets the value of the informationOwner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInformationOwner(String value) {
        this.informationOwner = value;
    }

    /**
     * Gets the value of the locationSignature property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationSignature() {
        return locationSignature;
    }

    /**
     * Sets the value of the locationSignature property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationSignature(String value) {
        this.locationSignature = value;
    }

    /**
     * Gets the value of the mobileWebLink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobileWebLink() {
        return mobileWebLink;
    }

    /**
     * Sets the value of the mobileWebLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobileWebLink(String value) {
        this.mobileWebLink = value;
    }

    /**
     * Gets the value of the modifiedTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getModifiedTime() {
        return modifiedTime;
    }

    /**
     * Sets the value of the modifiedTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setModifiedTime(XMLGregorianCalendar value) {
        this.modifiedTime = value;
    }

    /**
     * Gets the value of the newEquipment property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNewEquipment() {
        return newEquipment;
    }

    /**
     * Sets the value of the newEquipment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNewEquipment(Integer value) {
        this.newEquipment = value;
    }

    /**
     * Gets the value of the operator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperator() {
        return operator;
    }

    /**
     * Sets the value of the operator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperator(String value) {
        this.operator = value;
    }

    /**
     * Gets the value of the otherInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OtherInformation }
     * 
     * 
     */
    public List<OtherInformation> getOtherInformation() {
        if (otherInformation == null) {
            otherInformation = new ArrayList<OtherInformation>();
        }
        return this.otherInformation;
    }

    /**
     * Gets the value of the plannedEstimatedTimeAtLocation property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPlannedEstimatedTimeAtLocation() {
        return plannedEstimatedTimeAtLocation;
    }

    /**
     * Sets the value of the plannedEstimatedTimeAtLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPlannedEstimatedTimeAtLocation(XMLGregorianCalendar value) {
        this.plannedEstimatedTimeAtLocation = value;
    }

    /**
     * Gets the value of the plannedEstimatedTimeAtLocationIsValid property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPlannedEstimatedTimeAtLocationIsValid() {
        return plannedEstimatedTimeAtLocationIsValid;
    }

    /**
     * Sets the value of the plannedEstimatedTimeAtLocationIsValid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPlannedEstimatedTimeAtLocationIsValid(Boolean value) {
        this.plannedEstimatedTimeAtLocationIsValid = value;
    }

    /**
     * Gets the value of the productInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductInformation }
     * 
     * 
     */
    public List<ProductInformation> getProductInformation() {
        if (productInformation == null) {
            productInformation = new ArrayList<ProductInformation>();
        }
        return this.productInformation;
    }

    /**
     * Gets the value of the scheduledDepartureDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getScheduledDepartureDateTime() {
        return scheduledDepartureDateTime;
    }

    /**
     * Sets the value of the scheduledDepartureDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setScheduledDepartureDateTime(XMLGregorianCalendar value) {
        this.scheduledDepartureDateTime = value;
    }

    /**
     * Gets the value of the service property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the service property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getService().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Service }
     * 
     * 
     */
    public List<Service> getService() {
        if (service == null) {
            service = new ArrayList<Service>();
        }
        return this.service;
    }

    /**
     * Gets the value of the technicalDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTechnicalDateTime() {
        return technicalDateTime;
    }

    /**
     * Sets the value of the technicalDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTechnicalDateTime(XMLGregorianCalendar value) {
        this.technicalDateTime = value;
    }

    /**
     * Gets the value of the technicalTrainIdent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTechnicalTrainIdent() {
        return technicalTrainIdent;
    }

    /**
     * Sets the value of the technicalTrainIdent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTechnicalTrainIdent(String value) {
        this.technicalTrainIdent = value;
    }

    /**
     * Gets the value of the timeAtLocation property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeAtLocation() {
        return timeAtLocation;
    }

    /**
     * Sets the value of the timeAtLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeAtLocation(XMLGregorianCalendar value) {
        this.timeAtLocation = value;
    }

    /**
     * Gets the value of the timeAtLocationWithSeconds property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeAtLocationWithSeconds() {
        return timeAtLocationWithSeconds;
    }

    /**
     * Sets the value of the timeAtLocationWithSeconds property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeAtLocationWithSeconds(XMLGregorianCalendar value) {
        this.timeAtLocationWithSeconds = value;
    }

    /**
     * Gets the value of the toLocation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the toLocation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getToLocation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ToLocation }
     * 
     * 
     */
    public List<ToLocation> getToLocation() {
        if (toLocation == null) {
            toLocation = new ArrayList<ToLocation>();
        }
        return this.toLocation;
    }

    /**
     * Gets the value of the trackAtLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrackAtLocation() {
        return trackAtLocation;
    }

    /**
     * Sets the value of the trackAtLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrackAtLocation(String value) {
        this.trackAtLocation = value;
    }

    /**
     * Gets the value of the trainComposition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trainComposition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrainComposition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TrainComposition }
     * 
     * 
     */
    public List<TrainComposition> getTrainComposition() {
        if (trainComposition == null) {
            trainComposition = new ArrayList<TrainComposition>();
        }
        return this.trainComposition;
    }

    /**
     * Gets the value of the trainOwner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrainOwner() {
        return trainOwner;
    }

    /**
     * Sets the value of the trainOwner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrainOwner(String value) {
        this.trainOwner = value;
    }

    /**
     * Gets the value of the typeOfTraffic property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the typeOfTraffic property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTypeOfTraffic().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TypeOfTraffic }
     * 
     * 
     */
    public List<TypeOfTraffic> getTypeOfTraffic() {
        if (typeOfTraffic == null) {
            typeOfTraffic = new ArrayList<TypeOfTraffic>();
        }
        return this.typeOfTraffic;
    }

    /**
     * Gets the value of the viaFromLocation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the viaFromLocation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getViaFromLocation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ViaFromLocation }
     * 
     * 
     */
    public List<ViaFromLocation> getViaFromLocation() {
        if (viaFromLocation == null) {
            viaFromLocation = new ArrayList<ViaFromLocation>();
        }
        return this.viaFromLocation;
    }

    /**
     * Gets the value of the viaToLocation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the viaToLocation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getViaToLocation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ViaToLocation }
     * 
     * 
     */
    public List<ViaToLocation> getViaToLocation() {
        if (viaToLocation == null) {
            viaToLocation = new ArrayList<ViaToLocation>();
        }
        return this.viaToLocation;
    }

    /**
     * Gets the value of the webLink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebLink() {
        return webLink;
    }

    /**
     * Sets the value of the webLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebLink(String value) {
        this.webLink = value;
    }

    /**
     * Gets the value of the webLinkName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebLinkName() {
        return webLinkName;
    }

    /**
     * Sets the value of the webLinkName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebLinkName(String value) {
        this.webLinkName = value;
    }

}
