//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.29 at 02:58:40 PM UTC 
//


package se.trixon.trv_traffic_information.road.weatherstation.v1;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Air complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Air"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Temp" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
 *         &lt;element name="TempIconId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RelativeHumidity" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Air", propOrder = {
    "temp",
    "tempIconId",
    "relativeHumidity"
})
public class Air {

    @XmlElement(name = "Temp")
    protected Float temp;
    @XmlElement(name = "TempIconId")
    protected String tempIconId;
    @XmlElement(name = "RelativeHumidity")
    protected Float relativeHumidity;

    /**
     * Gets the value of the temp property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getTemp() {
        return temp;
    }

    /**
     * Sets the value of the temp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setTemp(Float value) {
        this.temp = value;
    }

    /**
     * Gets the value of the tempIconId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTempIconId() {
        return tempIconId;
    }

    /**
     * Sets the value of the tempIconId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTempIconId(String value) {
        this.tempIconId = value;
    }

    /**
     * Gets the value of the relativeHumidity property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getRelativeHumidity() {
        return relativeHumidity;
    }

    /**
     * Sets the value of the relativeHumidity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setRelativeHumidity(Float value) {
        this.relativeHumidity = value;
    }

}
