//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.29 at 02:44:43 PM UTC 
//


package se.trixon.trv_trafikinformation.vag.measurementdata100.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for MeasurementData100 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MeasurementData100"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="County" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="RoadMainNumber" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="RoadSubNumber" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Direction" type="{}Direction" minOccurs="0"/&gt;
 *         &lt;element name="Lane" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="StartContinuousLength" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="EndContinuousLength" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Length" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="MeasurementDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="MeasurementDateSpecific" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="MeasurementDataType" type="{}MeasurementDataType"/&gt;
 *         &lt;element name="IRIRightAverageValue" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="EdgeDepthAverageValue" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="RutDepthMax15AverageValue" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="RutDepthMax17AverageValue" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="MPDMacrotextureAverageValue" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="TimeStamp" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="ModifiedTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="Deleted" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MeasurementData100", propOrder = {
    "county",
    "roadMainNumber",
    "roadSubNumber",
    "direction",
    "lane",
    "startContinuousLength",
    "endContinuousLength",
    "length",
    "measurementDate",
    "measurementDateSpecific",
    "measurementDataType",
    "iriRightAverageValue",
    "edgeDepthAverageValue",
    "rutDepthMax15AverageValue",
    "rutDepthMax17AverageValue",
    "mpdMacrotextureAverageValue",
    "timeStamp",
    "modifiedTime",
    "deleted"
})
public class MeasurementData100 {

    @XmlElement(name = "County")
    protected int county;
    @XmlElement(name = "RoadMainNumber")
    protected int roadMainNumber;
    @XmlElement(name = "RoadSubNumber")
    protected int roadSubNumber;
    @XmlElement(name = "Direction")
    protected Direction direction;
    @XmlElement(name = "Lane")
    protected int lane;
    @XmlElement(name = "StartContinuousLength")
    protected int startContinuousLength;
    @XmlElement(name = "EndContinuousLength")
    protected int endContinuousLength;
    @XmlElement(name = "Length")
    protected int length;
    @XmlElement(name = "MeasurementDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar measurementDate;
    @XmlElement(name = "MeasurementDateSpecific", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar measurementDateSpecific;
    @XmlElement(name = "MeasurementDataType", required = true)
    protected MeasurementDataType measurementDataType;
    @XmlElement(name = "IRIRightAverageValue")
    protected double iriRightAverageValue;
    @XmlElement(name = "EdgeDepthAverageValue")
    protected double edgeDepthAverageValue;
    @XmlElement(name = "RutDepthMax15AverageValue")
    protected double rutDepthMax15AverageValue;
    @XmlElement(name = "RutDepthMax17AverageValue")
    protected double rutDepthMax17AverageValue;
    @XmlElement(name = "MPDMacrotextureAverageValue")
    protected double mpdMacrotextureAverageValue;
    @XmlElement(name = "TimeStamp", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeStamp;
    @XmlElement(name = "ModifiedTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar modifiedTime;
    @XmlElement(name = "Deleted")
    protected Boolean deleted;

    /**
     * Gets the value of the county property.
     * 
     */
    public int getCounty() {
        return county;
    }

    /**
     * Sets the value of the county property.
     * 
     */
    public void setCounty(int value) {
        this.county = value;
    }

    /**
     * Gets the value of the roadMainNumber property.
     * 
     */
    public int getRoadMainNumber() {
        return roadMainNumber;
    }

    /**
     * Sets the value of the roadMainNumber property.
     * 
     */
    public void setRoadMainNumber(int value) {
        this.roadMainNumber = value;
    }

    /**
     * Gets the value of the roadSubNumber property.
     * 
     */
    public int getRoadSubNumber() {
        return roadSubNumber;
    }

    /**
     * Sets the value of the roadSubNumber property.
     * 
     */
    public void setRoadSubNumber(int value) {
        this.roadSubNumber = value;
    }

    /**
     * Gets the value of the direction property.
     * 
     * @return
     *     possible object is
     *     {@link Direction }
     *     
     */
    public Direction getDirection() {
        return direction;
    }

    /**
     * Sets the value of the direction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Direction }
     *     
     */
    public void setDirection(Direction value) {
        this.direction = value;
    }

    /**
     * Gets the value of the lane property.
     * 
     */
    public int getLane() {
        return lane;
    }

    /**
     * Sets the value of the lane property.
     * 
     */
    public void setLane(int value) {
        this.lane = value;
    }

    /**
     * Gets the value of the startContinuousLength property.
     * 
     */
    public int getStartContinuousLength() {
        return startContinuousLength;
    }

    /**
     * Sets the value of the startContinuousLength property.
     * 
     */
    public void setStartContinuousLength(int value) {
        this.startContinuousLength = value;
    }

    /**
     * Gets the value of the endContinuousLength property.
     * 
     */
    public int getEndContinuousLength() {
        return endContinuousLength;
    }

    /**
     * Sets the value of the endContinuousLength property.
     * 
     */
    public void setEndContinuousLength(int value) {
        this.endContinuousLength = value;
    }

    /**
     * Gets the value of the length property.
     * 
     */
    public int getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     */
    public void setLength(int value) {
        this.length = value;
    }

    /**
     * Gets the value of the measurementDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMeasurementDate() {
        return measurementDate;
    }

    /**
     * Sets the value of the measurementDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMeasurementDate(XMLGregorianCalendar value) {
        this.measurementDate = value;
    }

    /**
     * Gets the value of the measurementDateSpecific property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMeasurementDateSpecific() {
        return measurementDateSpecific;
    }

    /**
     * Sets the value of the measurementDateSpecific property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMeasurementDateSpecific(XMLGregorianCalendar value) {
        this.measurementDateSpecific = value;
    }

    /**
     * Gets the value of the measurementDataType property.
     * 
     * @return
     *     possible object is
     *     {@link MeasurementDataType }
     *     
     */
    public MeasurementDataType getMeasurementDataType() {
        return measurementDataType;
    }

    /**
     * Sets the value of the measurementDataType property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasurementDataType }
     *     
     */
    public void setMeasurementDataType(MeasurementDataType value) {
        this.measurementDataType = value;
    }

    /**
     * Gets the value of the iriRightAverageValue property.
     * 
     */
    public double getIRIRightAverageValue() {
        return iriRightAverageValue;
    }

    /**
     * Sets the value of the iriRightAverageValue property.
     * 
     */
    public void setIRIRightAverageValue(double value) {
        this.iriRightAverageValue = value;
    }

    /**
     * Gets the value of the edgeDepthAverageValue property.
     * 
     */
    public double getEdgeDepthAverageValue() {
        return edgeDepthAverageValue;
    }

    /**
     * Sets the value of the edgeDepthAverageValue property.
     * 
     */
    public void setEdgeDepthAverageValue(double value) {
        this.edgeDepthAverageValue = value;
    }

    /**
     * Gets the value of the rutDepthMax15AverageValue property.
     * 
     */
    public double getRutDepthMax15AverageValue() {
        return rutDepthMax15AverageValue;
    }

    /**
     * Sets the value of the rutDepthMax15AverageValue property.
     * 
     */
    public void setRutDepthMax15AverageValue(double value) {
        this.rutDepthMax15AverageValue = value;
    }

    /**
     * Gets the value of the rutDepthMax17AverageValue property.
     * 
     */
    public double getRutDepthMax17AverageValue() {
        return rutDepthMax17AverageValue;
    }

    /**
     * Sets the value of the rutDepthMax17AverageValue property.
     * 
     */
    public void setRutDepthMax17AverageValue(double value) {
        this.rutDepthMax17AverageValue = value;
    }

    /**
     * Gets the value of the mpdMacrotextureAverageValue property.
     * 
     */
    public double getMPDMacrotextureAverageValue() {
        return mpdMacrotextureAverageValue;
    }

    /**
     * Sets the value of the mpdMacrotextureAverageValue property.
     * 
     */
    public void setMPDMacrotextureAverageValue(double value) {
        this.mpdMacrotextureAverageValue = value;
    }

    /**
     * Gets the value of the timeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeStamp() {
        return timeStamp;
    }

    /**
     * Sets the value of the timeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeStamp(XMLGregorianCalendar value) {
        this.timeStamp = value;
    }

    /**
     * Gets the value of the modifiedTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getModifiedTime() {
        return modifiedTime;
    }

    /**
     * Sets the value of the modifiedTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setModifiedTime(XMLGregorianCalendar value) {
        this.modifiedTime = value;
    }

    /**
     * Gets the value of the deleted property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDeleted() {
        return deleted;
    }

    /**
     * Sets the value of the deleted property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDeleted(Boolean value) {
        this.deleted = value;
    }

}
