//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.10.03 at 07:39:30 AM UTC 
//


package se.trixon.trv_traffic_information.road.weatherobservation.v2_1;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 				Air conditions, atmospheric conditions close to the ground.
 * 			
 * 
 * <p>Java class for AirCondition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AirCondition"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Temperature" type="{}CelsiusMeasure" minOccurs="0"/&gt;
 *         &lt;element name="Dewpoint" type="{}CelsiusMeasure" minOccurs="0"/&gt;
 *         &lt;element name="RelativeHumidity" type="{}PercentageMeasure" minOccurs="0"/&gt;
 *         &lt;element name="VisibleDistance" type="{}MetersMeasure" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AirCondition", propOrder = {
    "temperature",
    "dewpoint",
    "relativeHumidity",
    "visibleDistance"
})
public class AirCondition {

    @XmlElement(name = "Temperature")
    protected CelsiusMeasure temperature;
    @XmlElement(name = "Dewpoint")
    protected CelsiusMeasure dewpoint;
    @XmlElement(name = "RelativeHumidity")
    protected PercentageMeasure relativeHumidity;
    @XmlElement(name = "VisibleDistance")
    protected MetersMeasure visibleDistance;

    /**
     * Gets the value of the temperature property.
     * 
     * @return
     *     possible object is
     *     {@link CelsiusMeasure }
     *     
     */
    public CelsiusMeasure getTemperature() {
        return temperature;
    }

    /**
     * Sets the value of the temperature property.
     * 
     * @param value
     *     allowed object is
     *     {@link CelsiusMeasure }
     *     
     */
    public void setTemperature(CelsiusMeasure value) {
        this.temperature = value;
    }

    /**
     * Gets the value of the dewpoint property.
     * 
     * @return
     *     possible object is
     *     {@link CelsiusMeasure }
     *     
     */
    public CelsiusMeasure getDewpoint() {
        return dewpoint;
    }

    /**
     * Sets the value of the dewpoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link CelsiusMeasure }
     *     
     */
    public void setDewpoint(CelsiusMeasure value) {
        this.dewpoint = value;
    }

    /**
     * Gets the value of the relativeHumidity property.
     * 
     * @return
     *     possible object is
     *     {@link PercentageMeasure }
     *     
     */
    public PercentageMeasure getRelativeHumidity() {
        return relativeHumidity;
    }

    /**
     * Sets the value of the relativeHumidity property.
     * 
     * @param value
     *     allowed object is
     *     {@link PercentageMeasure }
     *     
     */
    public void setRelativeHumidity(PercentageMeasure value) {
        this.relativeHumidity = value;
    }

    /**
     * Gets the value of the visibleDistance property.
     * 
     * @return
     *     possible object is
     *     {@link MetersMeasure }
     *     
     */
    public MetersMeasure getVisibleDistance() {
        return visibleDistance;
    }

    /**
     * Sets the value of the visibleDistance property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetersMeasure }
     *     
     */
    public void setVisibleDistance(MetersMeasure value) {
        this.visibleDistance = value;
    }

}
