//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.10.03 at 07:39:30 AM UTC 
//


package se.trixon.trv_traffic_information.road.weatherobservation.v2_1;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GripMeasure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GripMeasure"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{}ValueMetadata"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Value" type="{}DecimalMeasure_0-1" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GripMeasure", propOrder = {
    "value"
})
public class GripMeasure
    extends ValueMetadata
{

    @XmlElement(name = "Value")
    protected DecimalMeasure01 value;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link DecimalMeasure01 }
     *     
     */
    public DecimalMeasure01 getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link DecimalMeasure01 }
     *     
     */
    public void setValue(DecimalMeasure01 value) {
        this.value = value;
    }

}
