//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.10.03 at 07:39:30 AM UTC 
//


package se.trixon.trv_traffic_information.road.weatherobservation.v2_1;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the se.trixon.trv_traffic_information.road.weatherobservation package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RESPONSE_QNAME = new QName("", "RESPONSE");
    private final static QName _Deleted_QNAME = new QName("", "Deleted");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: se.trixon.trv_traffic_information.road.weatherobservation
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RESPONSE }
     * 
     */
    public RESPONSE createRESPONSE() {
        return new RESPONSE();
    }

    /**
     * Create an instance of {@link RESULT }
     * 
     */
    public RESULT createRESULT() {
        return new RESULT();
    }

    /**
     * Create an instance of {@link ERROR }
     * 
     */
    public ERROR createERROR() {
        return new ERROR();
    }

    /**
     * Create an instance of {@link LASTMODIFIED }
     * 
     */
    public LASTMODIFIED createLASTMODIFIED() {
        return new LASTMODIFIED();
    }

    /**
     * Create an instance of {@link EVALRESULT }
     * 
     */
    public EVALRESULT createEVALRESULT() {
        return new EVALRESULT();
    }

    /**
     * Create an instance of {@link INFO }
     * 
     */
    public INFO createINFO() {
        return new INFO();
    }

    /**
     * Create an instance of {@link WeatherObservation }
     * 
     */
    public WeatherObservation createWeatherObservation() {
        return new WeatherObservation();
    }

    /**
     * Create an instance of {@link ObservationBase }
     * 
     */
    public ObservationBase createObservationBase() {
        return new ObservationBase();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link Weather }
     * 
     */
    public Weather createWeather() {
        return new Weather();
    }

    /**
     * Create an instance of {@link SurfaceCondition }
     * 
     */
    public SurfaceCondition createSurfaceCondition() {
        return new SurfaceCondition();
    }

    /**
     * Create an instance of {@link AirCondition }
     * 
     */
    public AirCondition createAirCondition() {
        return new AirCondition();
    }

    /**
     * Create an instance of {@link WindCondition }
     * 
     */
    public WindCondition createWindCondition() {
        return new WindCondition();
    }

    /**
     * Create an instance of {@link DeicingChemical }
     * 
     */
    public DeicingChemical createDeicingChemical() {
        return new DeicingChemical();
    }

    /**
     * Create an instance of {@link SubsurfaceCondition }
     * 
     */
    public SubsurfaceCondition createSubsurfaceCondition() {
        return new SubsurfaceCondition();
    }

    /**
     * Create an instance of {@link Aggregated5Minutes }
     * 
     */
    public Aggregated5Minutes createAggregated5Minutes() {
        return new Aggregated5Minutes();
    }

    /**
     * Create an instance of {@link Aggregated10Minutes }
     * 
     */
    public Aggregated10Minutes createAggregated10Minutes() {
        return new Aggregated10Minutes();
    }

    /**
     * Create an instance of {@link Aggregated30Minutes }
     * 
     */
    public Aggregated30Minutes createAggregated30Minutes() {
        return new Aggregated30Minutes();
    }

    /**
     * Create an instance of {@link Geometry }
     * 
     */
    public Geometry createGeometry() {
        return new Geometry();
    }

    /**
     * Create an instance of {@link CelsiusMeasure }
     * 
     */
    public CelsiusMeasure createCelsiusMeasure() {
        return new CelsiusMeasure();
    }

    /**
     * Create an instance of {@link BoolMeasure }
     * 
     */
    public BoolMeasure createBoolMeasure() {
        return new BoolMeasure();
    }

    /**
     * Create an instance of {@link GripMeasure }
     * 
     */
    public GripMeasure createGripMeasure() {
        return new GripMeasure();
    }

    /**
     * Create an instance of {@link MillimetersMeasure }
     * 
     */
    public MillimetersMeasure createMillimetersMeasure() {
        return new MillimetersMeasure();
    }

    /**
     * Create an instance of {@link SnowAmount }
     * 
     */
    public SnowAmount createSnowAmount() {
        return new SnowAmount();
    }

    /**
     * Create an instance of {@link PercentageMeasure }
     * 
     */
    public PercentageMeasure createPercentageMeasure() {
        return new PercentageMeasure();
    }

    /**
     * Create an instance of {@link MetersMeasure }
     * 
     */
    public MetersMeasure createMetersMeasure() {
        return new MetersMeasure();
    }

    /**
     * Create an instance of {@link MetersPerSecondMeasure }
     * 
     */
    public MetersPerSecondMeasure createMetersPerSecondMeasure() {
        return new MetersPerSecondMeasure();
    }

    /**
     * Create an instance of {@link DegreesMeasure }
     * 
     */
    public DegreesMeasure createDegreesMeasure() {
        return new DegreesMeasure();
    }

    /**
     * Create an instance of {@link GramPerSquareMeterMeasure }
     * 
     */
    public GramPerSquareMeterMeasure createGramPerSquareMeterMeasure() {
        return new GramPerSquareMeterMeasure();
    }

    /**
     * Create an instance of {@link GroundCondition }
     * 
     */
    public GroundCondition createGroundCondition() {
        return new GroundCondition();
    }

    /**
     * Create an instance of {@link Aggregated }
     * 
     */
    public Aggregated createAggregated() {
        return new Aggregated();
    }

    /**
     * Create an instance of {@link ValueMetadata }
     * 
     */
    public ValueMetadata createValueMetadata() {
        return new ValueMetadata();
    }

    /**
     * Create an instance of {@link DecimalMeasure }
     * 
     */
    public DecimalMeasure createDecimalMeasure() {
        return new DecimalMeasure();
    }

    /**
     * Create an instance of {@link DecimalMeasure01 }
     * 
     */
    public DecimalMeasure01 createDecimalMeasure01() {
        return new DecimalMeasure01();
    }

    /**
     * Create an instance of {@link DecimalMeasure0100 }
     * 
     */
    public DecimalMeasure0100 createDecimalMeasure0100() {
        return new DecimalMeasure0100();
    }

    /**
     * Create an instance of {@link IntMeasure0360 }
     * 
     */
    public IntMeasure0360 createIntMeasure0360() {
        return new IntMeasure0360();
    }

    /**
     * Create an instance of {@link IntegerCentimetersConfig }
     * 
     */
    public IntegerCentimetersConfig createIntegerCentimetersConfig() {
        return new IntegerCentimetersConfig();
    }

    /**
     * Create an instance of {@link WindConditionAggregated }
     * 
     */
    public WindConditionAggregated createWindConditionAggregated() {
        return new WindConditionAggregated();
    }

    /**
     * Create an instance of {@link PrecipitationConditionAggregated }
     * 
     */
    public PrecipitationConditionAggregated createPrecipitationConditionAggregated() {
        return new PrecipitationConditionAggregated();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RESPONSE }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RESPONSE }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "RESPONSE")
    public JAXBElement<RESPONSE> createRESPONSE(RESPONSE value) {
        return new JAXBElement<RESPONSE>(_RESPONSE_QNAME, RESPONSE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Deleted", defaultValue = "false")
    public JAXBElement<Boolean> createDeleted(Boolean value) {
        return new JAXBElement<Boolean>(_Deleted_QNAME, Boolean.class, null, value);
    }

}
