//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.10.03 at 07:39:30 AM UTC 
//


package se.trixon.trv_traffic_information.road.weatherobservation.v2_1;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ValueMetadata complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ValueMetadata"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Origin" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="calculated"/&gt;
 *               &lt;enumeration value="measured"/&gt;
 *               &lt;enumeration value="estimated"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="SensorNames" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ValueMetadata", propOrder = {
    "origin",
    "sensorNames"
})
@XmlSeeAlso({
    CelsiusMeasure.class,
    GripMeasure.class,
    MillimetersMeasure.class,
    PercentageMeasure.class,
    MetersMeasure.class,
    MetersPerSecondMeasure.class,
    DegreesMeasure.class,
    GramPerSquareMeterMeasure.class,
    IntegerCentimetersConfig.class
})
public class ValueMetadata {

    @XmlElement(name = "Origin")
    protected String origin;
    @XmlElement(name = "SensorNames")
    protected String sensorNames;

    /**
     * Gets the value of the origin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * Sets the value of the origin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigin(String value) {
        this.origin = value;
    }

    /**
     * Gets the value of the sensorNames property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSensorNames() {
        return sensorNames;
    }

    /**
     * Sets the value of the sensorNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSensorNames(String value) {
        this.sensorNames = value;
    }

}
