//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.10.03 at 07:39:30 AM UTC 
//


package se.trixon.trv_traffic_information.road.weatherobservation.v2_1;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import java.math.BigInteger;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for WeatherObservation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WeatherObservation"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{}ObservationBase"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Measurepoint" type="{}Location" minOccurs="0"/&gt;
 *         &lt;element ref="{}Deleted" minOccurs="0"/&gt;
 *         &lt;element name="ModifiedTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{}QueueAttributes"/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WeatherObservation", propOrder = {
    "id",
    "measurepoint",
    "deleted",
    "modifiedTime"
})
public class WeatherObservation
    extends ObservationBase
{

    @XmlElement(name = "Id")
    protected String id;
    @XmlElement(name = "Measurepoint")
    protected Location measurepoint;
    @XmlElement(name = "Deleted", defaultValue = "false")
    protected Boolean deleted;
    @XmlElement(name = "ModifiedTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar modifiedTime;
    @XmlAttribute(name = "checkoutid")
    protected String checkoutid;
    @XmlAttribute(name = "checkouts")
    protected BigInteger checkouts;
    @XmlAttribute(name = "leaseduntil")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar leaseduntil;
    @XmlAttribute(name = "acknowledged")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar acknowledged;
    @XmlAttribute(name = "statuscode")
    @XmlSchemaType(name = "unsignedByte")
    protected Short statuscode;
    @XmlAttribute(name = "itemsacknowledged")
    protected Long itemsacknowledged;
    @XmlAttribute(name = "itemsleft")
    protected Long itemsleft;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the measurepoint property.
     * 
     * @return
     *     possible object is
     *     {@link Location }
     *     
     */
    public Location getMeasurepoint() {
        return measurepoint;
    }

    /**
     * Sets the value of the measurepoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link Location }
     *     
     */
    public void setMeasurepoint(Location value) {
        this.measurepoint = value;
    }

    /**
     * Gets the value of the deleted property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDeleted() {
        return deleted;
    }

    /**
     * Sets the value of the deleted property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDeleted(Boolean value) {
        this.deleted = value;
    }

    /**
     * Gets the value of the modifiedTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getModifiedTime() {
        return modifiedTime;
    }

    /**
     * Sets the value of the modifiedTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setModifiedTime(XMLGregorianCalendar value) {
        this.modifiedTime = value;
    }

    /**
     * Gets the value of the checkoutid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCheckoutid() {
        return checkoutid;
    }

    /**
     * Sets the value of the checkoutid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCheckoutid(String value) {
        this.checkoutid = value;
    }

    /**
     * Gets the value of the checkouts property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCheckouts() {
        return checkouts;
    }

    /**
     * Sets the value of the checkouts property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCheckouts(BigInteger value) {
        this.checkouts = value;
    }

    /**
     * Gets the value of the leaseduntil property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLeaseduntil() {
        return leaseduntil;
    }

    /**
     * Sets the value of the leaseduntil property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLeaseduntil(XMLGregorianCalendar value) {
        this.leaseduntil = value;
    }

    /**
     * Gets the value of the acknowledged property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAcknowledged() {
        return acknowledged;
    }

    /**
     * Sets the value of the acknowledged property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAcknowledged(XMLGregorianCalendar value) {
        this.acknowledged = value;
    }

    /**
     * Gets the value of the statuscode property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getStatuscode() {
        return statuscode;
    }

    /**
     * Sets the value of the statuscode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setStatuscode(Short value) {
        this.statuscode = value;
    }

    /**
     * Gets the value of the itemsacknowledged property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getItemsacknowledged() {
        return itemsacknowledged;
    }

    /**
     * Sets the value of the itemsacknowledged property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setItemsacknowledged(Long value) {
        this.itemsacknowledged = value;
    }

    /**
     * Gets the value of the itemsleft property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getItemsleft() {
        return itemsleft;
    }

    /**
     * Sets the value of the itemsleft property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setItemsleft(Long value) {
        this.itemsleft = value;
    }

}
