//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.29 at 02:58:40 PM UTC 
//


package se.trixon.trv_trafikinformation.vag.weatherstation.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Measurement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Measurement"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MeasureTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="Precipitation" type="{}Precipitation" minOccurs="0"/&gt;
 *         &lt;element name="Road" type="{}Road" minOccurs="0"/&gt;
 *         &lt;element name="Air" type="{}Air" minOccurs="0"/&gt;
 *         &lt;element name="Wind" type="{}Wind" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Measurement", propOrder = {
    "measureTime",
    "precipitation",
    "road",
    "air",
    "wind"
})
public class Measurement {

    @XmlElement(name = "MeasureTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar measureTime;
    @XmlElement(name = "Precipitation")
    protected Precipitation precipitation;
    @XmlElement(name = "Road")
    protected Road road;
    @XmlElement(name = "Air")
    protected Air air;
    @XmlElement(name = "Wind")
    protected Wind wind;

    /**
     * Gets the value of the measureTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMeasureTime() {
        return measureTime;
    }

    /**
     * Sets the value of the measureTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMeasureTime(XMLGregorianCalendar value) {
        this.measureTime = value;
    }

    /**
     * Gets the value of the precipitation property.
     * 
     * @return
     *     possible object is
     *     {@link Precipitation }
     *     
     */
    public Precipitation getPrecipitation() {
        return precipitation;
    }

    /**
     * Sets the value of the precipitation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Precipitation }
     *     
     */
    public void setPrecipitation(Precipitation value) {
        this.precipitation = value;
    }

    /**
     * Gets the value of the road property.
     * 
     * @return
     *     possible object is
     *     {@link Road }
     *     
     */
    public Road getRoad() {
        return road;
    }

    /**
     * Sets the value of the road property.
     * 
     * @param value
     *     allowed object is
     *     {@link Road }
     *     
     */
    public void setRoad(Road value) {
        this.road = value;
    }

    /**
     * Gets the value of the air property.
     * 
     * @return
     *     possible object is
     *     {@link Air }
     *     
     */
    public Air getAir() {
        return air;
    }

    /**
     * Sets the value of the air property.
     * 
     * @param value
     *     allowed object is
     *     {@link Air }
     *     
     */
    public void setAir(Air value) {
        this.air = value;
    }

    /**
     * Gets the value of the wind property.
     * 
     * @return
     *     possible object is
     *     {@link Wind }
     *     
     */
    public Wind getWind() {
        return wind;
    }

    /**
     * Sets the value of the wind property.
     * 
     * @param value
     *     allowed object is
     *     {@link Wind }
     *     
     */
    public void setWind(Wind value) {
        this.wind = value;
    }

}
