//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.29 at 02:58:40 PM UTC 
//


package se.trixon.trv_trafikinformation.vag.weatherstation.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Road complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Road"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Temp" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
 *         &lt;element name="TempIconId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Road", propOrder = {
    "temp",
    "tempIconId"
})
public class Road {

    @XmlElement(name = "Temp")
    protected Float temp;
    @XmlElement(name = "TempIconId")
    protected String tempIconId;

    /**
     * Gets the value of the temp property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getTemp() {
        return temp;
    }

    /**
     * Sets the value of the temp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setTemp(Float value) {
        this.temp = value;
    }

    /**
     * Gets the value of the tempIconId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTempIconId() {
        return tempIconId;
    }

    /**
     * Sets the value of the tempIconId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTempIconId(String value) {
        this.tempIconId = value;
    }

}
