//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.29 at 02:46:46 PM UTC 
//


package se.trixon.trv_ti.road.surface.roaddata.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for RoadData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RoadData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="County" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="RoadMainNumber" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="RoadSubNumber" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Direction" type="{}Direction" minOccurs="0"/&gt;
 *         &lt;element name="LaneDescription" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="StartContinuousLength" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="EndContinuousLength" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Length" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="BearingCapacity" type="{}BearingCapacity" minOccurs="0"/&gt;
 *         &lt;element name="SpeedLimit" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="WearLayer" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="AADT" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="AADTHeavyVehicles" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="AADTMeasurementYear" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="AADTMeasurementMethod" type="{}AADTMeasurementMethod" minOccurs="0"/&gt;
 *         &lt;element name="RoadWidth" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="RoadOwner" type="{}RoadOwner" minOccurs="0"/&gt;
 *         &lt;element name="RoadCategory" type="{}RoadCategory" minOccurs="0"/&gt;
 *         &lt;element name="RoadType" type="{}RoadType" minOccurs="0"/&gt;
 *         &lt;element name="Winter2003" type="{}Winter2003" minOccurs="0"/&gt;
 *         &lt;element name="RoadConstruction2009" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="TimeStamp" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="ModifiedTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="Deleted" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RoadData", propOrder = {
    "county",
    "roadMainNumber",
    "roadSubNumber",
    "direction",
    "laneDescription",
    "startContinuousLength",
    "endContinuousLength",
    "length",
    "bearingCapacity",
    "speedLimit",
    "wearLayer",
    "aadt",
    "aadtHeavyVehicles",
    "aadtMeasurementYear",
    "aadtMeasurementMethod",
    "roadWidth",
    "roadOwner",
    "roadCategory",
    "roadType",
    "winter2003",
    "roadConstruction2009",
    "timeStamp",
    "modifiedTime",
    "deleted"
})
public class RoadData {

    @XmlElement(name = "County")
    protected int county;
    @XmlElement(name = "RoadMainNumber")
    protected int roadMainNumber;
    @XmlElement(name = "RoadSubNumber")
    protected int roadSubNumber;
    @XmlElement(name = "Direction")
    protected Direction direction;
    @XmlElement(name = "LaneDescription")
    protected int laneDescription;
    @XmlElement(name = "StartContinuousLength")
    protected int startContinuousLength;
    @XmlElement(name = "EndContinuousLength")
    protected int endContinuousLength;
    @XmlElement(name = "Length")
    protected int length;
    @XmlElement(name = "BearingCapacity")
    protected BearingCapacity bearingCapacity;
    @XmlElement(name = "SpeedLimit")
    protected int speedLimit;
    @XmlElement(name = "WearLayer")
    protected int wearLayer;
    @XmlElement(name = "AADT")
    protected int aadt;
    @XmlElement(name = "AADTHeavyVehicles")
    protected int aadtHeavyVehicles;
    @XmlElement(name = "AADTMeasurementYear")
    protected int aadtMeasurementYear;
    @XmlElement(name = "AADTMeasurementMethod")
    protected AADTMeasurementMethod aadtMeasurementMethod;
    @XmlElement(name = "RoadWidth")
    protected double roadWidth;
    @XmlElement(name = "RoadOwner")
    protected RoadOwner roadOwner;
    @XmlElement(name = "RoadCategory")
    protected RoadCategory roadCategory;
    @XmlElement(name = "RoadType")
    protected RoadType roadType;
    @XmlElement(name = "Winter2003")
    protected Winter2003 winter2003;
    @XmlElement(name = "RoadConstruction2009")
    protected int roadConstruction2009;
    @XmlElement(name = "TimeStamp", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeStamp;
    @XmlElement(name = "ModifiedTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar modifiedTime;
    @XmlElement(name = "Deleted")
    protected Boolean deleted;

    /**
     * Gets the value of the county property.
     * 
     */
    public int getCounty() {
        return county;
    }

    /**
     * Sets the value of the county property.
     * 
     */
    public void setCounty(int value) {
        this.county = value;
    }

    /**
     * Gets the value of the roadMainNumber property.
     * 
     */
    public int getRoadMainNumber() {
        return roadMainNumber;
    }

    /**
     * Sets the value of the roadMainNumber property.
     * 
     */
    public void setRoadMainNumber(int value) {
        this.roadMainNumber = value;
    }

    /**
     * Gets the value of the roadSubNumber property.
     * 
     */
    public int getRoadSubNumber() {
        return roadSubNumber;
    }

    /**
     * Sets the value of the roadSubNumber property.
     * 
     */
    public void setRoadSubNumber(int value) {
        this.roadSubNumber = value;
    }

    /**
     * Gets the value of the direction property.
     * 
     * @return
     *     possible object is
     *     {@link Direction }
     *     
     */
    public Direction getDirection() {
        return direction;
    }

    /**
     * Sets the value of the direction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Direction }
     *     
     */
    public void setDirection(Direction value) {
        this.direction = value;
    }

    /**
     * Gets the value of the laneDescription property.
     * 
     */
    public int getLaneDescription() {
        return laneDescription;
    }

    /**
     * Sets the value of the laneDescription property.
     * 
     */
    public void setLaneDescription(int value) {
        this.laneDescription = value;
    }

    /**
     * Gets the value of the startContinuousLength property.
     * 
     */
    public int getStartContinuousLength() {
        return startContinuousLength;
    }

    /**
     * Sets the value of the startContinuousLength property.
     * 
     */
    public void setStartContinuousLength(int value) {
        this.startContinuousLength = value;
    }

    /**
     * Gets the value of the endContinuousLength property.
     * 
     */
    public int getEndContinuousLength() {
        return endContinuousLength;
    }

    /**
     * Sets the value of the endContinuousLength property.
     * 
     */
    public void setEndContinuousLength(int value) {
        this.endContinuousLength = value;
    }

    /**
     * Gets the value of the length property.
     * 
     */
    public int getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     */
    public void setLength(int value) {
        this.length = value;
    }

    /**
     * Gets the value of the bearingCapacity property.
     * 
     * @return
     *     possible object is
     *     {@link BearingCapacity }
     *     
     */
    public BearingCapacity getBearingCapacity() {
        return bearingCapacity;
    }

    /**
     * Sets the value of the bearingCapacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BearingCapacity }
     *     
     */
    public void setBearingCapacity(BearingCapacity value) {
        this.bearingCapacity = value;
    }

    /**
     * Gets the value of the speedLimit property.
     * 
     */
    public int getSpeedLimit() {
        return speedLimit;
    }

    /**
     * Sets the value of the speedLimit property.
     * 
     */
    public void setSpeedLimit(int value) {
        this.speedLimit = value;
    }

    /**
     * Gets the value of the wearLayer property.
     * 
     */
    public int getWearLayer() {
        return wearLayer;
    }

    /**
     * Sets the value of the wearLayer property.
     * 
     */
    public void setWearLayer(int value) {
        this.wearLayer = value;
    }

    /**
     * Gets the value of the aadt property.
     * 
     */
    public int getAADT() {
        return aadt;
    }

    /**
     * Sets the value of the aadt property.
     * 
     */
    public void setAADT(int value) {
        this.aadt = value;
    }

    /**
     * Gets the value of the aadtHeavyVehicles property.
     * 
     */
    public int getAADTHeavyVehicles() {
        return aadtHeavyVehicles;
    }

    /**
     * Sets the value of the aadtHeavyVehicles property.
     * 
     */
    public void setAADTHeavyVehicles(int value) {
        this.aadtHeavyVehicles = value;
    }

    /**
     * Gets the value of the aadtMeasurementYear property.
     * 
     */
    public int getAADTMeasurementYear() {
        return aadtMeasurementYear;
    }

    /**
     * Sets the value of the aadtMeasurementYear property.
     * 
     */
    public void setAADTMeasurementYear(int value) {
        this.aadtMeasurementYear = value;
    }

    /**
     * Gets the value of the aadtMeasurementMethod property.
     * 
     * @return
     *     possible object is
     *     {@link AADTMeasurementMethod }
     *     
     */
    public AADTMeasurementMethod getAADTMeasurementMethod() {
        return aadtMeasurementMethod;
    }

    /**
     * Sets the value of the aadtMeasurementMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link AADTMeasurementMethod }
     *     
     */
    public void setAADTMeasurementMethod(AADTMeasurementMethod value) {
        this.aadtMeasurementMethod = value;
    }

    /**
     * Gets the value of the roadWidth property.
     * 
     */
    public double getRoadWidth() {
        return roadWidth;
    }

    /**
     * Sets the value of the roadWidth property.
     * 
     */
    public void setRoadWidth(double value) {
        this.roadWidth = value;
    }

    /**
     * Gets the value of the roadOwner property.
     * 
     * @return
     *     possible object is
     *     {@link RoadOwner }
     *     
     */
    public RoadOwner getRoadOwner() {
        return roadOwner;
    }

    /**
     * Sets the value of the roadOwner property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoadOwner }
     *     
     */
    public void setRoadOwner(RoadOwner value) {
        this.roadOwner = value;
    }

    /**
     * Gets the value of the roadCategory property.
     * 
     * @return
     *     possible object is
     *     {@link RoadCategory }
     *     
     */
    public RoadCategory getRoadCategory() {
        return roadCategory;
    }

    /**
     * Sets the value of the roadCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoadCategory }
     *     
     */
    public void setRoadCategory(RoadCategory value) {
        this.roadCategory = value;
    }

    /**
     * Gets the value of the roadType property.
     * 
     * @return
     *     possible object is
     *     {@link RoadType }
     *     
     */
    public RoadType getRoadType() {
        return roadType;
    }

    /**
     * Sets the value of the roadType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoadType }
     *     
     */
    public void setRoadType(RoadType value) {
        this.roadType = value;
    }

    /**
     * Gets the value of the winter2003 property.
     * 
     * @return
     *     possible object is
     *     {@link Winter2003 }
     *     
     */
    public Winter2003 getWinter2003() {
        return winter2003;
    }

    /**
     * Sets the value of the winter2003 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Winter2003 }
     *     
     */
    public void setWinter2003(Winter2003 value) {
        this.winter2003 = value;
    }

    /**
     * Gets the value of the roadConstruction2009 property.
     * 
     */
    public int getRoadConstruction2009() {
        return roadConstruction2009;
    }

    /**
     * Sets the value of the roadConstruction2009 property.
     * 
     */
    public void setRoadConstruction2009(int value) {
        this.roadConstruction2009 = value;
    }

    /**
     * Gets the value of the timeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeStamp() {
        return timeStamp;
    }

    /**
     * Sets the value of the timeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeStamp(XMLGregorianCalendar value) {
        this.timeStamp = value;
    }

    /**
     * Gets the value of the modifiedTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getModifiedTime() {
        return modifiedTime;
    }

    /**
     * Sets the value of the modifiedTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setModifiedTime(XMLGregorianCalendar value) {
        this.modifiedTime = value;
    }

    /**
     * Gets the value of the deleted property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDeleted() {
        return deleted;
    }

    /**
     * Sets the value of the deleted property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDeleted(Boolean value) {
        this.deleted = value;
    }

}
